# Utiliza una imagen de Node.js como base

FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor

WORKDIR /app

# Copia los archivos de la aplicación al contenedor

COPY package*.json ./

COPY . .

# Instala las dependencias

RUN npm install

# Compila la aplicación Next.js

RUN npm run build

# Expone el puerto en el que se ejecuta la aplicación

EXPOSE 3000

# Comando de inicio

CMD ["npm", "start"]